let URL='http://localhost:3000'
const CommonApi={
   loginUrl:{
    url:URL+'/login',
    method:'POST'
   },
   signupUrl:{
    url:URL+'/signup',
    method:'POST'
   },
   authData:{
    url:URL+'/user-Detail',
    method:'GET'
   },
   logout:{
url:URL+'/logout',
    method:'DELETE'
   },
   AllStudents:{
      url:URL+'/all-student',
    method:'GET'
   },
   AllTeacher:{
       url:URL+'/all-teacher',
    method:'GET'
   },
   SingleStudents:{
      url:URL+'/student-Id',
    method:'GET'
   },
   SingleTeacher:{
      url:URL+'/teacher-Id',
    method:'PUT'
   },
   SingleTeacherEdit:{
       url:URL+'/teacher-Id',
    method:'GET'
   },
   SingleStudentsEdit:{
        url:URL+'/students-Id',
    method:'PUT'
   },
   DeleteStudent:{
       url:URL+'/delete-student',
    method:'DELETE'
   },
   classAdd:{
         url:URL+'/add-class',
    method:'POST'
   },
   allClass:{
         url:URL+'/all-class',
    method:'GET'
   },
   ClassDetail:{
       url:URL+'/classDetils',
    method:'GET'
   },
   classDetilsEdit:{
      url:URL+'/classDetils-edit',
      method:'PUT' 
   },
   DeleteClasss:{
      url:URL+'/delete-class',
      method:'DELETE'
   },
   allClassAssignPrinciple:{
           url:URL+'/principle-assign-class',
      method:'GET'
   }
   
}
export default CommonApi;